helpers/authentication.js
fixes https://github.com/schul-cloud/superhero-dashboard/issues/1
=> remove redirect loop and go through all roles

views/lib/loggedin.hbs
=> making it special

controllers/helpdesk.js, controllers/index.js, controllers/login.js, controllers/management.js, controllers/roles.js, controllers/schools.js, controllers/users.js, helpers/authentication.js, static/scripts/schools.js, views/helpdesk/forms/form-problem.hbs, views/helpdesk/helpdesk.hbs, views/management/management.hbs, views/schools/schools.hbs, views/users/preselect.hbs, views/users/users.hbs
fixes https://github.com/schul-cloud/superhero-dashboard/issues/5 and also provides a search bar for users/schools and ports the helpdesk from client
=> make all tables sortable

controllers/users.js, views/users/jwt.hbs
https://github.com/schul-cloud/superhero-dashboard/issues/12
=> create the option to login as user

controllers/users.js, static/scripts/schools.js, views/users/users.hbs
done https://github.com/schul-cloud/superhero-dashboard/issues/10
=> search in selected school and general improvements

controllers/federalstates.js, controllers/helpdesk.js, controllers/roles.js, controllers/schools.js, controllers/users.js, static/scripts/schools.js, views/lib/components/table.hbs
dones https://github.com/schul-cloud/superhero-dashboard/issues/16
=> add limit changer for tables

controllers/accounts.js, controllers/index.js, controllers/users.js, helpers/authentication.js, views/accounts/accounts.hbs, views/accounts/forms/add-account.hbs, views/accounts/search.hbs
closes https://github.com/schul-cloud/superhero-dashboard/issues/15
=> add accounts page and specific button for user

controllers/accounts.js, controllers/users.js
closes https://github.com/schul-cloud/superhero-dashboard/issues/19
=> add further functionality for account page

Dockerfile, docker-compose.yml, package.json
- Checkout branch
```
cd superhero-dashboard
docker build -t schulcloud/superhero-dashboard .
docker run -it -p 3033:3033 -e BACKEND_URL=https://schul-cloud.org:8080/ superhero-dashboard
```
- Checkout branch
- Edit `docker-compose.yml` and `BACKEND_URL`
```
docker-compose up
```
=> Add Dockerfile & docker-compose.yml

controllers/users.js
=> fix cutoff invitation mail

controllers/accounts.js, controllers/federalstates.js, controllers/helpdesk.js, controllers/roles.js, controllers/schools.js, controllers/users.js, views/lib/components/table.hbs, views/users/jwt.hbs
ticket: https://ticketsystem.schul-cloud.org/browse/SC-204
=> SC-204-Buttons haben keine Hover-Beschreibungstexte

views/users/forms/add-user.hbs
should be checked by the server but for now, at least add a pattern to the input field
=> add password pattern for superhero add user

controllers/account.js, controllers/users.js, views/account/settings.hbs
Kombi-PR für [SC-618](https://ticketsystem.schul-cloud.org/browse/SC-618) und [SC-646](https://ticketsystem.schul-cloud.org/browse/SC-646), da diese miteinander zusammenhängen und dieselben Dateien betroffen sind.
Benötigt [Client](https://github.com/schul-cloud/schulcloud-client/pull/1016)- und [Server](https://github.com/schul-cloud/schulcloud-server/pull/456)-PR.
=> Geschlecht u. Forschung entfernen

controllers/statistics.js
E.g. current statistics output, from `https://api.schul-cloud.org/statistics`
```
{
"users": 8474,
"schools": 132,
"accounts": 5848,
"homework": 1587,
"submissions": 3882,
"comments": 50,
"lessons": 2619,
"classes": 476,
"courses": 1283,
"teachers": 1566,
"students": 4835,
"files/directories": 14599
}
=> Adjust to backend statistics route

controllers/accounts.js, controllers/schools.js, controllers/users.js
[SC-1102](https://ticketsystem.schul-cloud.org/browse/SC-1102)
=> make search case-insensitiv

controllers/users.js
Ticket: https://ticketsystem.schul-cloud.org/browse/SC-1175
Client-PR: https://github.com/schul-cloud/schulcloud-client/pull/1157
Server-PR: https://github.com/schul-cloud/schulcloud-server/pull/564
=> SC-1175 Prozess und Texte der Einverst.erkl. an Kanzleivorgaben anpassen

controllers/users.js
Now all schools are loaded in user section
=> SC-877 fix SHD school limit

controllers/index.js, controllers/tools.js, helpers/authentication.js, package-lock.json, static/scripts/tools.js, views/tools/forms/add-tool.hbs, views/tools/tools.hbs
Enables superhero to create, update and delete tools and corresponding OAuth2 clients
=> Add tool management

controllers/tools.js, views/tools/forms/add-tool.hbs, views/tools/tools.hbs
In tool management show urls of oauth2 endpoints.
Needs backend PR: https://github.com/schul-cloud/schulcloud-server/pull/749
=> Display OAuth2 endpoints

controllers/users.js
- https://github.com/schul-cloud/schulcloud-server/pull/859
=> cleanup code

controllers/schools.js
Use correct file schema (including (new) required fields)
=> Fix: Create an empty file to create a bucket for a newly created school

.travis.yml, Dockerfile
Dockertags für K8s-Deployment angepasst
=> Dockertag4k8s

controllers/tools.js, views/tools/forms/add-tool.hbs
Related to 
https://github.com/schul-cloud/schulcloud-client/pull/1647
https://github.com/schul-cloud/schulcloud-server/pull/993
Expands configuration for scopes and auto skip consent
=> E-Mail und Name für OAuth2 mit OpenIDConnect

controllers/index.js, controllers/schools.js, controllers/storageproviders.js, helpers/authentication.js, views/storageproviders/forms/add-storageprovider.hbs, views/storageproviders/storageproviders.hbs
Fügt eine Verwaltung für die File Storage Provider hinzu und dient zur Überwachung ihrer Kapazitäten.
Braucht: https://github.com/schul-cloud/schulcloud-server/pull/1074
Ticket: https://ticketsystem.schul-cloud.org/browse/SC-2922
=> Feature/SC-2922/Use multiple s3-providers per instance

controllers/management.js
- https://github.com/schul-cloud/schulcloud-server/pull/1132
- https://ticketsystem.schul-cloud.org/browse/SC-3395
=> SC-3395 | Display error if releases fetch failed

package-lock.json, package.json, views/schools/schools.hbs
Just fixed the wrong URl.... the old one added the term search as id
=> Fix school search

controllers/schools.js, package-lock.json, package.json, views/schools/forms/add-school.hbs
select timezone when creating school
- https://ticketsystem.hpi-schul-cloud.org/browse/SC-2710
- Superhero Dashboard: https://github.com/hpi-schul-cloud/superhero-dashboard/pull/86
Added timezone property to school form
"moment-timezone": "^0.5.31",
to get all timezones
=> Feature/SC-2710 - Implementing time zones

controllers/users.js
Creating new users via SHD via "silent creation" (user+account creation) isn't working. User object is created, with import hash, account is not created, error:
```
importHash missing
Fehler-Details
StatusCodeError: 400 - {"name":"BadRequest","message":"importHash missing","code":400,"className":"bad-request","data":{"requestId":"5f7b2d9355a1940029df5255"},"errors":{}} 
```
https://ticketsystem.hpi-schul-cloud.org/browse/SC-7081
- Added required and missing importHash parameter to "registrationPins" call.
=> Hotfix/1/SC-7081 - Can't create users via SHD anymore

controllers/schools.js, helpers/timeZoneHelper.js, views/schools/forms/add-school.hbs
=> Timezone refactoring.

CHANGELOG.md, package-lock.json, package.json
Creating new users via SHD via "silent creation" (user+account creation) isn't working. User object is created, with import hash, account is not created, error:
```
importHash missing
Fehler-Details
StatusCodeError: 400 - {"name":"BadRequest","message":"importHash missing","code":400,"className":"bad-request","data":{"requestId":"5f7b2d9355a1940029df5255"},"errors":{}} 
```
https://ticketsystem.hpi-schul-cloud.org/browse/SC-7081
- Added required and missing importHash parameter to "registrationPins" call.
=> Hotfix/1/SC-7081 - Can't create users via SHD anymore (Update)

CHANGELOG.md, controllers/users.js
There was a bug as described in https://ticketsystem.hpi-schul-cloud.org/browse/SC-7758 
We fixed it by rebuilding the request a bit. Luckily these changes are limited to the SHD and do not impact the server. 
Due to Prettier formatting the whole file it is quite hard to understand what we changed. 
Basically we built a new request to /users/. This is done from line 270 to 324.
=> SC-7758 fixed cannot read user information

CHANGELOG.md, views/management/management.hbs
Changed some namings in section for uploading new consent versions.
https://ticketsystem.hpi-schul-cloud.org/browse/SC-8247
=> changed namings of consent table and modal for uploading new consent version

CHANGELOG.md, static/scripts/management.js, views/management/management.hbs
=> fix for namings

app.js
https://ticketsystem.hpi-schul-cloud.org/browse/SC-7483
set limit per env or default value to 4mb
There is one new env (BODYPARSER_LIMIT) but default is 4mb
=> fix limit of bodyparser

CHANGELOG.md, controllers/schools.js
On the schools page, sometimes the page itself was not loading (leading to 500).
Other times, clicking on the edit icon for one school was not opening the popup.
- https://ticketsystem.schul-cloud.org/browse/SC-9041
=> SC-9041 - fixes error which leads to crush on schools page

CHANGELOG.md, controllers/users.js
- https://ticketsystem.schul-cloud.org/browse/SC-9177
=> SC-9177 allow superheros to delete admins

CHANGELOG.md, api.js, package-lock.json, package.json
access server api by dedicated version prefix. currently only `/v1` for the feathers api is used.
=> SC-9192 Fix path mapping

CHANGELOG.md, ansible/roles/superhero-dashboard/templates/deployment.yml.j2
Reduce resource consumption for deployed nuxtclient.
https://ticketsystem.hpi-schul-cloud.org/browse/BC-37
https://ticketsystem.hpi-schul-cloud.org/browse/BC-57
Make CPU and memory resource consumption configurable.
Set the default for memory to be between 128mb and 4gb.
Set the default pod count to 1 pod
=> BC-37 - BC-57 - reduce resource consumption for deployed Superhero Dashboard

CHANGELOG.md
Add ansible files for Bosscloud (default)
https://ticketsystem.hpi-schul-cloud.org/browse/BC-38
https://ticketsystem.hpi-schul-cloud.org/browse/BC-129
hpi-schul-cloud/schulcloud-server#2939
hpi-schul-cloud/schulcloud-client#2664
hpi-schul-cloud/nuxt-client#1882
hpi-schul-cloud/schulcloud-calendar#88
hpi-schul-cloud/schulcloud-editor#75
hpi-schul-cloud/dof_app_deploy#29
Add ansible files for Bosscloud (default)
=> BC-38 - BC-129 - Add ansible files for Bosscloud (default)

CHANGELOG.md, ansible/group_vars/all/superhero-dashboard.yml, ansible/roles/superhero-dashboard/templates/deployment.yml.j2
=> BC-740 change ansible vars for docker image and tag

CHANGELOG.md, ansible/roles/superhero-dashboard/tasks/main.yml, ansible/roles/superhero-dashboard/templates/ingress.yml.j2, ansible/roles/superhero-dashboard/templates/onepassword_basic_auth.yml.j2, ansible/roles/superhero-dashboard/templates/secret_basic_auth.yml.j2
Sort and split ansible rols
hpi-schul-cloud/dof_app_deploy#69
hpi-schul-cloud/nuxt-client#1986
hpi-schul-cloud/schulcloud-server#3233
hpi-schul-cloud/schulcloud-client#2730
hpi-schul-cloud/schulcloud-calendar#99
https://ticketsystem.hpi-schul-cloud.org/browse/BC-741
=> BC-741 - Sort and split ansible rols

package-lock.json, package.json
=> bump version 27.0.0

ansible/roles/superhero-dashboard/meta/main.yml
hpi-schul-cloud/antivirus_check_service#19
hpi-schul-cloud/dof_app_deploy#84
hpi-schul-cloud/nuxt-client#2017
hpi-schul-cloud/schulcloud-calendar#106
hpi-schul-cloud/schulcloud-client#2743
hpi-schul-cloud/schulcloud-server#3270
https://ticketsystem.hpi-schul-cloud.org/browse/BC-1006
=> BC-1006 - Meta file for the roles

ansible/roles/superhero-dashboard/templates/ingress.yml.j2
Added possibility to specify a cluster issuer using the CLUSTER_ISSUER ansible variable
hpi-schul-cloud/dof_app_deploy#175
=> OPS-3191 Added cluster issuer to ingress

controllers/tools.js, package-lock.json, views/tools/forms/add-tool.hbs
Added hidden flag for tools
https://ticketsystem.dbildungscloud.de/browse/N21-90
=> N21-90 Added hidden flag for tools

controllers/login.js
Before adapting the auto-logout method to the one used for regular platform (take inactivity into consideration), the lifetime of the SHD JWT needs to be adjusted from 1 hour to 2 hours.
BC-2527
=> BC-2527 - Increase SHD JWT token lifetime

controllers/login.js
=> fix autologout

ansible/roles/superhero-dashboard/templates/ingress.yml.j2
Ingress with API version extensions/v1beta1 and networking.k8s.io/v1beta1 were deprecated, with Kubernetes 1.22 they are moved to networking.k8s.io/v1, this requires some small template changes, see https://awstip.com/upgrading-kubernetes-ingresses-from-v1beta1-to-v1-7f9235765332
https://ticketsystem.dbildungscloud.de/browse/OPS-3919
=> OPS-3919 update to kubernetes 1.22.15

views/ctltools/ctltools.hbs, views/ctltools/forms/delete-form.hbs
- change text for ctl delete modal
https://github.com/hpi-schul-cloud/schulcloud-server/pull/3745
https://ticketsystem.dbildungscloud.de/browse/N21-450
https://ticketsystem.dbildungscloud.de/browse/N21-410
=> N21-450 CTL Delete

controllers/accounts.js
https://ticketsystem.dbildungscloud.de/browse/BC-2334
Create "DELETE USER" after deleting account.
=> BC-2334 fix deleting account

controllers/ctltools.js, static/scripts/ctltools.js, views/ctltools/forms/add-ctl-tool.hbs
Expands the custom parameter attributes when configuring an external tool by a superhero.
Adds a mandatory regexComment field when the regex field is is filled.
Adds an isOptional flag to toggle optionality of a custom parameter.
https://ticketsystem.dbildungscloud.de/browse/N21-479
https://ticketsystem.dbildungscloud.de/browse/N21-477
https://github.com/hpi-schul-cloud/schulcloud-server/pull/3773
=> N21-479 new ctltool attributes

controllers/ctltools.js, static/scripts/ctltools.js, static/scripts/tools.js, views/ctltools/forms/add-ctl-tool.hbs
Replaced put to post for updating tools
https://ticketsystem.dbildungscloud.de/browse/N21-408
https://ticketsystem.dbildungscloud.de/browse/N21-511
=> N21-408 Update external tool

.github/workflows/clean.yml, .github/workflows/push.yml, .github/workflows/tag.yml
=> BC-2889 limit workflow permissions

package-lock.json, package.json
This reverts commit 5a530456e2298d6be674951c547e2df34937c9f7.
The commit was breaking the startup of SHD.
Another solution for the security alert regarding jwt needs to be found.
https://ticketsystem.dbildungscloud.de/browse/BC-2937
=> Revert "BC-2937 - update jsonwebtoken to v9 (#193)"

controllers/ctltools.js
Removed unnecessary create parameter in sanitizing method of ctl tool
https://ticketsystem.dbildungscloud.de/browse/N21-530
=> N21-530 Fixes oauth2 ctl tools update

controllers/ctltools.js, static/scripts/ctltools.js
N21-241 Changed property default name to defaultValue because openapi generator makes this property private as _default
=> N21-241 Changed property name default to defaultValue

Dockerfile
=> Add bin to dockerfile

controllers/schools.js
Change date formatting
https://ticketsystem.dbildungscloud.de/browse/N21-799
=> N21-799 wrong time zone 

controllers/ctltools.js, static/scripts/ctltools.js, views/ctltools/forms/add-ctl-tool.hbs
- adapt modal for model changes
https://ticketsystem.dbildungscloud.de/browse/N21-595
https://github.com/hpi-schul-cloud/nuxt-client/pull/2474
https://github.com/hpi-schul-cloud/schulcloud-server/pull/4037
=> N21-595 Extend CTL Model

helpers/authentication.js
reverse ctl and lti feature flag
https://ticketsystem.dbildungscloud.de/browse/N21-869
=> N21-869 reverse ctl and lti feature flag

.github/workflows/tag.yml
https://ticketsystem.dbildungscloud.de/browse/BC-3778
=> BC-3778 push container image to quay

controllers/schools.js
- change school api call to use migration entity
https://ticketsystem.dbildungscloud.de/browse/N21-845
=> N21-845 Adapt SHD school list for usage of UserLoginMigrationEntity

controllers/schools.js, views/schools/forms/add-school.hbs
adds the functionality that a superhero can enable/disable the feature "oauthProvisioningEnabled" for a school
https://ticketsystem.dbildungscloud.de/browse/N21-958
=> N21-958 add feature oauthProvisioningEnabled

ansible/group_vars/all/superhero-dashboard.yml
https://ticketsystem.dbildungscloud.de/browse/BC-4316
https://github.com/hpi-schul-cloud/schulcloud-calendar/pull/139
https://github.com/hpi-schul-cloud/schulcloud-server/pull/4207
https://github.com/hpi-schul-cloud/version-aggregator/pull/8
https://github.com/hpi-schul-cloud/schulcloud-client/pull/3217
https://github.com/hpi-schul-cloud/nuxt-client/pull/2599
https://github.com/hpi-schul-cloud/superhero-dashboard/pull/214
https://github.com/hpi-schul-cloud/antivirus_check_service/pull/37
=> BC-4316 pull images for ref and prod from quay.io

views/schools/forms/add-school.hbs
After changing validation of official schoolnumber this adapts the description of the field
https://ticketsystem.dbildungscloud.de/browse/N21-1012
https://github.com/hpi-schul-cloud/schulcloud-server/pull/4195
=> N21-1012 change schoolnumber description

ansible/group_vars/develop/superhero-dashboard.yml
Removed feature flag from internal ansible FEATURE_CTL_TOOLS_ENABLED 
https://ticketsystem.dbildungscloud.de/browse/N21-1098
https://github.com/hpi-schul-cloud/dof_app_deploy/pull/593
=> N21-1098 FEATURE_CTL_TOOLS_ENABLED moved to dof app

static/scripts/ctltools.js, views/ctltools/forms/add-ctl-tool.hbs
adds a validation message which values can be set as default value for boolean type
https://ticketsystem.dbildungscloud.de/browse/N21-1047
=> N21-1047 add description for type boolean for ctl tools

controllers/ctltools.js, controllers/tools.js
https://ticketsystem.dbildungscloud.de/browse/N21-1058
https://github.com/hpi-schul-cloud/schulcloud-server/pull/4294
https://github.com/hpi-schul-cloud/nuxt-client/pull/2705
=> N21-1058 - refactor ctl api endpoints

static/scripts/ctltools.js, views/ctltools/forms/add-ctl-tool.hbs
The info text for default values is always displayed for Boolean custom parameters
https://ticketsystem.dbildungscloud.de/browse/N21-1162
=> N21-1162 fix displays Boolean info

controllers/schools.js, static/scripts/schools.js, views/lib/components/table.hbs
Fixes the sorting of user login migrations, because it's not possible to sort on virtual mongodb objects, it will be sorted on client side.
https://ticketsystem.dbildungscloud.de/browse/N21-754
=> N21-754 fix sorting of user login migrations

controllers/schools.js
adds enableSyncDuringMigration school feature
https://ticketsystem.dbildungscloud.de/browse/N21-1192
https://github.com/hpi-schul-cloud/nuxt-client/pull/2761
https://github.com/hpi-schul-cloud/schulcloud-server/pull/4351
https://github.com/hpi-schul-cloud/dof_app_deploy/pull/616
=> N21-1192 add enableLdapSyncDuringMigration

README.md, controllers/accounts.js
The updatedAt value for accounts was added to the Superhero Dashboard display.
https://ticketsystem.dbildungscloud.de/browse/EW-547
https://github.com/hpi-schul-cloud/schulcloud-server/pull/4357
https://github.com/hpi-schul-cloud/nuxt-client/pull/2770
=> EW-547 Showing updatedAt information in the SHD

ansible/roles/superhero-dashboard/templates/ingress.yml.j2
Chance how the ingress is selected in accord to the ingess definitiv from kubernetes. Remove the old label and Set it to the spec field
hpi-schul-cloud/dof_app_deploy#645
https://ticketsystem.dbildungscloud.de/browse/BC-5163
=> BC-5163 - change ingress class seting to spec

ansible/roles/superhero-dashboard/templates/ingress.yml.j2
change ingress rule pathType from ImplementationSpecific to Prefix
https://ticketsystem.dbildungscloud.de/browse/BC-5197
hpi-schul-cloud/dof_app_deploy#647
=> BC-5197 - change ingress rule pathType to Prefix

.github/workflows/push.yml, ansible/roles/superhero-dashboard/templates/deployment.yml.j2
We need additional Metadata for the git repo, branch/tag, commit hash and the [common-labels](https://kubernetes.io/docs/concepts/overview/working-with-objects/common-labels/#labels) for our kubernetes Deployments and Pods.
BC-5405
https://github.com/hpi-schul-cloud/schulcloud-server/pull/4517
https://github.com/hpi-schul-cloud/schulcloud-client/pull/3343
https://github.com/hpi-schul-cloud/dof_app_deploy/pull/689
https://github.com/hpi-schul-cloud/nuxt-client/pull/2899
https://github.com/hpi-schul-cloud/schulcloud-calendar/pull/150
https://github.com/hpi-schul-cloud/antivirus_check_service/pull/43
https://github.com/hpi-schul-cloud/version-aggregator/pull/12
https://github.com/hpi-schul-cloud/h5p-staticfiles-server/pull/5
> Notice: Please remove the WIP label if the PR is ready to review, …
=> BC-5405 - Metadata on k8s ressources

controllers/ctltools.js, static/scripts/ctltools.js, static/styles/ctltools/ctltools.scss, views/ctltools/forms/delete-form.hbs
https://ticketsystem.dbildungscloud.de/browse/N21-1319
https://github.com/hpi-schul-cloud/schulcloud-server/pull/4543
https://github.com/hpi-schul-cloud/nuxt-client/pull/2922
=> N21-1319 ctl showing tool usage

controllers/ctltools.js, views/ctltools/forms/add-ctl-tool.hbs
Adding the functionality that the SHD can limit a CTL tool to certain context
https://ticketsystem.dbildungscloud.de/browse/N21-1298
https://github.com/hpi-schul-cloud/schulcloud-server/pull/4579
https://github.com/hpi-schul-cloud/nuxt-client/pull/2929
=> N21-1298 tool context restrictions 

.github/workflows/clean.yml, .github/workflows/push.yml, .github/workflows/tag.yml
https://ticketsystem.dbildungscloud.de/browse/BC-5855
https://github.com/hpi-schul-cloud/schulcloud-server/pull/4655
https://github.com/hpi-schul-cloud/schulcloud-client/pull/3374
https://github.com/hpi-schul-cloud/h5p-staticfiles-server/pull/8
https://github.com/hpi-schul-cloud/superhero-dashboard/pull/240
https://github.com/hpi-schul-cloud/nuxt-client/pull/2964
https://github.com/hpi-schul-cloud/antivirus_check_service/pull/49
https://github.com/hpi-schul-cloud/version-aggregator/pull/16
=> BC-5658 update gh-actions, remove dof_bingo

controllers/ctltools.js, static/scripts/ctltools.js, views/ctltools/forms/add-ctl-tool.hbs
add protected attribute to CTL custom parameter
https://ticketsystem.dbildungscloud.de/browse/N21-1587
https://github.com/hpi-schul-cloud/schulcloud-server/pull/4658
https://github.com/hpi-schul-cloud/nuxt-client/pull/2968
=> N21-1587 protected custom parameter

controllers/ctltools.js, views/ctltools/forms/add-ctl-tool.hbs
adds isDeactivated parameter to CTL tool
https://ticketsystem.dbildungscloud.de/browse/N21-1421
=> N21-1421 handle tool deactivation

controllers/tools.js
When trying to open the "Tools" section / page of the "superhero-dashboard" (SHD) the user gets an "504 Gateway Time-out" and the page won't open.
https://ticketsystem.dbildungscloud.de/browse/BC-6205
Link to deployments :
https://bc-6205-fix-lti-tools.dbc.dbildungscloud.dev/
https://bc-6205-fix-lti-tools.nbc.dbildungscloud.dev/
https://bc-6205-fix-lti-tools.brb.dbildungscloud.dev/
Link to superhero-dashboard :
https://shd-bc-6205-fix-lti-tools.dbc.dbildungscloud.dev/
https://shd-bc-6205-fix-lti-tools.nbc.dbildungscloud.dev/
https://shd-bc-6205-fix-lti-tools.brb.dbildungscloud.dev/
=> BC-6205 - "504 Gateway Time-out" when trying to open "Tools" page in SHD

controllers/tools.js
When trying to add a new "LTI Tool" in the "Tools" section / page of the "superhero-dashboard" (SHD) the user gets an 404 Page not found" and the tool won't be added.
https://ticketsystem.dbildungscloud.de/browse/BC-6257
Link to deployments :
https://bc-6257-fix-add-lti-tools.dbc.dbildungscloud.dev/
https://bc-6257-fix-add-lti-tools.nbc.dbildungscloud.dev/
https://bc-6257-fix-add-lti-tools.brb.dbildungscloud.dev/
Link to superhero-dashboard :
https://shd-bc-6257-fix-add-lti-tools.dbc.dbildungscloud.dev/
https://shd-bc-6257-fix-add-lti-tools.nbc.dbildungscloud.dev/
https://shd-bc-6257-fix-add-lti-tools.brb.dbildungscloud.dev/
=> BC-6257 - Unable to add "LTI Tool"

controllers/ctltools.js, views/lib/components/table.hbs
This PR adds a datasheet button to the external tool list in /ctltools. Clicking the button results in the creation of a pdf with all relevant information about the tool which will be displayed directly in a new tab.
- https://ticketsystem.dbildungscloud.de/browse/N21-1626
- https://github.com/hpi-schul-cloud/schulcloud-server/pull/4717
- https://github.com/hpi-schul-cloud/nuxt-client/pull/3063
=> N21-1626 ctl data sheet

controllers/tools.js, static/scripts/schools.js, static/styles/schools/schools.scss, views/schools/forms/add-school.hbs, views/schools/schools.hbs
Bugfix for missing school feature 'enableLdapSyncDuringMigration'
https://ticketsystem.dbildungscloud.de/browse/N21-1681
=> N21-1681 missing school feature

.github/workflows/clean.yml, .github/workflows/push.yml, .github/workflows/tag.yml, ansible/roles/superhero-dashboard/templates/ingress.yml.j2
https://ticketsystem.dbildungscloud.de/browse/BC-6589
https://github.com/hpi-schul-cloud/schulcloud-server/pull/4771
https://github.com/hpi-schul-cloud/schulcloud-client/pull/3414
https://github.com/hpi-schul-cloud/nuxt-client/pull/3112
https://github.com/hpi-schul-cloud/superhero-dashboard/pull/250
https://github.com/hpi-schul-cloud/schulcloud-calendar/pull/157
https://github.com/hpi-schul-cloud/antivirus_check_service/pull/52
https://github.com/hpi-schul-cloud/version-aggregator/pull/19
https://github.com/hpi-schul-cloud/dof_app_deploy/pull/798
https://github.com/hpi-schul-cloud/h5p-staticfiles-server/pull/9
https://github.com/hpi-schul-cloud/tldraw-client/pull/58
=> BC-6589 update gh-actions

controllers/ctltools.js, views/ctltools/forms/add-ctl-tool.hbs
https://ticketsystem.dbildungscloud.de/browse/N21-1768
https://github.com/hpi-schul-cloud/schulcloud-server/pull/4784
=> N21-1768 fix CTL LTI resource_link_id

controllers/ctltools.js, views/ctltools/forms/add-ctl-tool.hbs
Adds new fields description, media id and publisher to ctl form
- https://ticketsystem.dbildungscloud.de/browse/N21-1836
- https://github.com/hpi-schul-cloud/schulcloud-server/pull/4876
=> N21-1836 extends ctl with description, media id and publisher

controllers/ctltools.js
- https://ticketsystem.dbildungscloud.de/browse/N21-1783
- https://github.com/hpi-schul-cloud/schulcloud-server/pull/4946
- https://github.com/hpi-schul-cloud/nuxt-client/pull/3214
=> N21-1783 Remove unused lti message type

views/ctltools/forms/add-ctl-tool.hbs
adds "Medienkatalog-Id" as a field in CTL Tools Medium. It is saved as "mediaSourceId"
- https://ticketsystem.dbildungscloud.de/browse/N21-1976
- https://github.com/hpi-schul-cloud/schulcloud-server/pull/5016
=> N21-1976 add Medienkatalog Id

controllers/ctltools.js
- https://ticketsystem.dbildungscloud.de/browse/N21-1825
- https://github.com/hpi-schul-cloud/schulcloud-server/pull/5155
- https://github.com/hpi-schul-cloud/nuxt-client/pull/3351
=> N21-1825 Group UUID auto param for synced course

.github/workflows/push.yml, ansible/roles/superhero-dashboard/tasks/main.yml
- hpi-schul-cloud/dof_app_deploy#936
- hpi-schul-cloud/schulcloud-client#3509
- hpi-schul-cloud/schulcloud-server#5189
- hpi-schul-cloud/nuxt-client#3365
- hpi-schul-cloud/tldraw-client#80
- hpi-schul-cloud/version-aggregator#21
- hpi-schul-cloud/h5p-staticfiles-server#11
- hpi-schul-cloud/schulcloud-calendar#163
- hpi-schul-cloud/antivirus_check_service#58
- hpi-schul-cloud/shd-client#7
- https://ticketsystem.dbildungscloud.de/browse/BC-7854
=> BC-7854 - split Ansible Jobs by Tags

views/users/forms/edit-user.hbs
- https://ticketsystem.dbildungscloud.de/browse/N21-2118
=> N21-2118 show deletion date of users

controllers/users.js
https://ticketsystem.dbildungscloud.de/browse/BC-8018
https://github.com/hpi-schul-cloud/schulcloud-server/pull/5248
https://github.com/hpi-schul-cloud/nuxt-client/pull/3408
https://github.com/hpi-schul-cloud/superhero-dashboard/pull/265
=> BC-8018 - refactor BC-8018 - API endpoint for retrieving JWT in users controller

ansible/roles/superhero-dashboard/templates/deployment.yml.j2
Add annotations to the kubernetes deployments so that they cann automaticly restart by the stakater reloader if configmaps or secrets change 
- hpi-schul-cloud/schulcloud-server#5265
- hpi-schul-cloud/dof_app_deploy#981
- hpi-schul-cloud/schulcloud-client#3527
- hpi-schul-cloud/nuxt-client#3413
- hpi-schul-cloud/shd-client#21
- hpi-schul-cloud/antivirus_check_service#64
- hpi-schul-cloud/schulcloud-calendar#164
- hpi-schul-cloud/version-aggregator#23
- hpi-schul-cloud/h5p-staticfiles-server#12
- hpi-schul-cloud/tldraw-server#20
- hpi-schul-cloud/tldraw-client#100
- https://ticketsystem.dbildungscloud.de/browse/BC-5112
=>  BC-5112 - add Annotations to deployment for Restart

controllers/ctltools.js, views/ctltools/forms/add-ctl-tool.hbs
allow superhero to create/update external tools to be preferred tools with icon
- https://ticketsystem.dbildungscloud.de/browse/N21-2166
- https://github.com/hpi-schul-cloud/schulcloud-server/pull/5259
- https://github.com/hpi-schul-cloud/dof_app_deploy/pull/980
- https://github.com/hpi-schul-cloud/nuxt-client/pull/3412
=> N21-2166 new fields to external tool form

controllers/ctltools.js, controllers/tools.js
- https://ticketsystem.dbildungscloud.de/browse/N21-2149
- https://github.com/hpi-schul-cloud/schulcloud-server/pull/5323
- https://github.com/hpi-schul-cloud/nuxt-client/pull/3446
=> N21 2149 merlin bibliothek element

README.md, package.json
https://ticketsystem.dbildungscloud.de/browse/BC-7994
=> BC-7994 Use node --watch instead of nodemon

ansible/roles/superhero-dashboard/templates/deployment.yml.j2
- https://ticketsystem.dbildungscloud.de/browse/BC-8876
- hpi-schul-cloud/dof_app_deploy#1100
- hpi-schul-cloud/schulcloud-server#5475
- hpi-schul-cloud/schulcloud-calendar#170
- hpi-schul-cloud/tldraw-server#52
- hpi-schul-cloud/antivirus_check_service#70
- hpi-schul-cloud/schulcloud-client#3577
- hpi-schul-cloud/nuxt-client#3530
- hpi-schul-cloud/version-aggregator#28
- hpi-schul-cloud/tldraw-client#123
- hpi-schul-cloud/h5p-staticfiles-server#17
- hpi-schul-cloud/shd-client#40
=> BC-8876 - add os to the pod template from the deployment

.github/workflows/dependency-review.yml, .github/workflows/push.yml
https://ticketsystem.dbildungscloud.de/browse/BC-9012
=> BC-9012 add dependabot ready-for-ci logic to push workflow

.github/workflows/push.yml
- https://ticketsystem.dbildungscloud.de/browse/BC-9058
=> BC-9058 - fix the branch_meta jo if the branch has no pr

views/users/forms/edit-user.hbs
- https://ticketsystem.dbildungscloud.de/browse/N21-2185
=> N21-2185 Change description for users "deletedAt" attribute

views/ctltools/forms/add-ctl-tool.hbs
- https://ticketsystem.dbildungscloud.de/browse/N21-2426
- https://github.com/hpi-schul-cloud/nuxt-client/pull/3599
=> N21-2426 Change wording for media

.github/workflows/push.yml
issue introduced in e3715a2f8c786e493aea2713c5029707ffb5dc3c
=> BC-9365 fixup push workflow

views/ctltools/forms/add-ctl-tool.hbs
- https://ticketsystem.dbildungscloud.de/browse/N21-2528
- https://github.com/hpi-schul-cloud/schulcloud-server/pull/5659
=> N21-2528 Add support for svg to external tool logos

.github/workflows/dependency-review.yml
https://ticketsystem.dbildungscloud.de/browse/BC-9800
https://github.com/hpi-schul-cloud/schulcloud-server/pull/5712
https://github.com/hpi-schul-cloud/schulcloud-client/pull/3644
https://github.com/hpi-schul-cloud/nuxt-client/pull/3715
https://github.com/hpi-schul-cloud/superhero-dashboard/pull/308
https://github.com/hpi-schul-cloud/schulcloud-calendar/pull/202
https://github.com/hpi-schul-cloud/antivirus_check_service/pull/90
https://github.com/hpi-schul-cloud/tldraw-client/pull/167
https://github.com/hpi-schul-cloud/dependency-review-config/pull/2
=> BC-9800 use centralized dependency-review-action config

controllers/ctltools.js
- add ctl custom parameter location option for anchor (URI fragment)
- https://ticketsystem.dbildungscloud.de/browse/N21-2529
- https://github.com/hpi-schul-cloud/schulcloud-server/pull/5739
- edit/create ctl form
=> N21-2529 external tool anchor parameter

controllers/ctltools.js, static/scripts/ctltools.js, views/ctltools/forms/add-ctl-tool.hbs
- fix missing ctl config fields after redirecting back from error page
- ctl tools view, frontend script & controller
=> N21-2575 fix missing ctl config fields after error

.github/workflows/push.yml, .github/workflows/trivy.yml
https://ticketsystem.dbildungscloud.de/browse/BC-10096
https://github.com/hpi-schul-cloud/schulcloud-server/pull/5783
https://github.com/hpi-schul-cloud/schulcloud-client/pull/3664
https://github.com/hpi-schul-cloud/nuxt-client/pull/3778
https://github.com/hpi-schul-cloud/superhero-dashboard/pull/315
https://github.com/hpi-schul-cloud/antivirus_check_service/pull/96
https://github.com/hpi-schul-cloud/version-aggregator/pull/37
https://github.com/hpi-schul-cloud/h5p-staticfiles-server/pull/21
https://github.com/hpi-schul-cloud/tldraw-client/pull/182
https://github.com/hpi-schul-cloud/tldraw-server/pull/68
https://github.com/hpi-schul-cloud/file-storage/pull/32
=> BC-10096 update gh-actions

controllers/schools.js, controllers/storageproviders.js
=> BC-10187 - Refactor school usages for readability and findability

controllers/ctltools.js
BC-10353
https://github.com/hpi-schul-cloud/schulcloud-server/pull/5871
https://github.com/hpi-schul-cloud/nuxt-client/pull/3889
=> BC-10353 - add publisher for ctl auto params
